"Build: Automation":
- .github/**
- .azuredevops/**

"Build: scripts & configs":
- build/**

"AL: System Application":
- src/System Application/**

"AL: Business Foundation":
- src/Business Foundation/**

"AL: Tools":
- src/Tools/**

"AL: Rulesets":
- src/Rulesets/**
