name: Run Automation
author: Microsoft Corporation
description: Get the official branches in the repository
inputs:
  automations:
    description: Comma-separated list of automations to run
  targetBranch:
    description: The target branch to run the automations on
runs:
  using: composite
  steps:
    - name: run
      shell: powershell
      id: runAutomation
      env:
        _repository: ${{ github.repository }}
        _actor: ${{ github.actor }}
        _automations: ${{ inputs.automations }}
        _targetBranch: ${{ inputs.targetBranch }}
      run: |
        ${{ github.action_path }}/build/scripts/Automations/run.ps1 -Include $env:_automations  -Repository $env:_repository -TargetBranch $env:_targetBranch -Actor $env:_actor
branding:
  icon: terminal
  color: blue
