name: Create issue for BC Idea I want to implement
description: Create issue for BC Idea you want to implement
title: "[BC Idea]: "
labels: ["bcidea"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a BC Idea issue!

        ⚠️⚠️ BEFORE WE GET STARTED ⚠️⚠️
        Please do not create an issue for a BC Idea unless you intend to implement it yourself. If you are not planning to implement the BC Idea yourself, please go to aka.ms/bcideas and upvote the feature on BC Ideas instead. 

        Before you create a new issue, please check the following:
        🔎 Search existing issues to avoid creating duplicates.
        🧪 Test using the latest bcinsider builds to see if your issue has already been fixed

        Read more about what and how to contribute in the CONTRIBUTIONS document of this repository: https://github.com/microsoft/BCApps/blob/main/CONTRIBUTING.md.

  - type: input
    id: bcidea
    attributes:
      label: BC Idea Link
      description: Please link to the BC Idea
      placeholder: ex. https://experience.dynamics.com/ideas/idea/?ideaid=123456
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please include the description from the BC Ideas page
      placeholder: Description of BC Idea
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: BC Idea Category
      description: What category is the BC Idea created under?
      options:
        - No Category
        - Data Migrations
        - Development
        - Documentation
        - Financial Management
        - General 
        - Geographies and Localization
        - Inventory
        - Manufacturing
        - Office Integration
        - Opportunity Management
        - Project Management
        - Purchasing
        - Reports and Business Intelligence
        - Sales
        - Service Order Managemen
        - Tenant Administration
        - Warehousing
      default: 0
    validations:
      required: true