blank_issues_enabled: false
contact_links:
  - name: Request a feature
    url: http://aka.ms/bcideas
    about: Please go to http://aka.ms/bcideas to log your idea. Creating an issue here is not the right way.
  - name: Report a bug which has customer impact
    url: http://aka.ms/bcsupport
    about: Please follow the steps on http://aka.ms/bcsupport to get support. Creating an issue here is not the right way.
