name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number 

pr: none
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

pool:
  name: 'd365bc-agentpool-nonprod-bcapps-sync'

variables:
- template: ./variables-common.yml

jobs:
- job: SyncMirror
  dependsOn: []
  steps:
  - task: powershell@2
    displayName: Set up repository
    inputs:
      targetType: 'inline'
      script: |
        function Get-AccessTokenFromManagedIdentity() {
          az login --identity --allow-no-subscriptions | Out-Null
          return (az account get-access-token | ConvertFrom-Json)
        }

        $MIAccessToken = Get-AccessTokenFromManagedIdentity

        git clone "https://$($MIAccessToken.accessToken)@$(TargetRepository)" BCApps
        Push-Location BCApps

        git config --global user.email "d365bc-agentpool-nonprod-bcapps-sync@microsoft.com"
        git config --global user.name "BCApps-Sync"
  - task: powershell@2
    displayName: Sync mirror with upstream
    inputs:
      filePath: Build\Scripts\SyncMirror.ps1
      arguments: '-SourceRepository "https://$(GitHubPAT)@github.com/microsoft/BCApps.git" -Branch $(Build.SourceBranch)'