name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number

pr: none
trigger: none
schedules:
- cron: '0 8 * * *'
  displayName: Daily Sync
  branches:
    include:
    - main
    - releases/*

pool:
  name: 'd365bc-agentpool-nonprod-bcapps-sync'

resources:
  repositories:
  - repository: PipelineTemplates
    type: git
    name: Infrastructure-PipelineTemplates
    ref: master

variables:
- template: ./variables-common.yml
- template: workitem-build-tracking-variables.yml@PipelineTemplates

jobs:
- job: SyncMirror
  dependsOn: []
  displayName: Sync mirror with upstream
  steps:
  - powershell: |
      git config --global user.email "BCApps-Sync@microsoft.com"
      git config --global user.name "BCApps-Sync"
    displayName: Update Git Config
  - task: powershell@2
    displayName: Sync mirror with upstream
    inputs:
      filePath: build\scripts\SyncMirror.ps1
      arguments: '-SourceRepository "https://github.com/microsoft/BCApps.git" -TargetRepository $(TargetRepository) -Branch $(Build.SourceBranch) -ManagedIdentityAuth'

- job: ReportBuildStatus
  dependsOn:
  - SyncMirror
  pool: 'd365bc-agentpool-nonprod-build-official'
  condition: failed()
  displayName: Report build status
  steps:
  - checkout: none
  - template: workitem-build-tracking.yml@PipelineTemplates
    parameters:
      Priority: '2'
      Severity: '2'
      Issue: 'Build Break'
      SecurityImpact: 'No'
      Condition: always()
