name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number

pr: none
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

variables:
- template: ./variables-common.yml

resources:
  repositories:
  - repository: Mirror
    type: git
    name: BCApps-Mirror
    ref: main

jobs:
- job: SyncMirror
  dependsOn: []
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: SyncMirror-Steps.yml
    parameters:
      SourceRepository: "$(MirrorRepo)" #"https://$(GitHubPAT)@github.com/microsoft/BCApps.git"
      Branch: "$(Build.SourceBranch)"