name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number 

pr: none
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  tags:
    include:
    - builds/*

pool:
  name: 'd365bc-agentpool-nonprod-bcapps-sync'

variables:
- template: ./variables-common.yml

jobs:
- job: SyncMirror
  dependsOn: []
  steps:
  - powershell: |
      git config --global user.email "BCApps-Sync@microsoft.com"
      git config --global user.name "BCApps-Sync"
    displayName: Update Git Config
  - task: powershell@2
    displayName: Sync mirror with upstream
    inputs:
      filePath: Build\Scripts\SyncMirror.ps1
      # If pipeline is triggered by a branch we sync the branch with latest changes from source repository
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads') }}:
        arguments: '-SourceRepository "https://$(GitHubPAT)@github.com/microsoft/BCApps.git" -TargetRepository $(TargetRepository) -Branch $(Build.SourceBranch) -ManagedIdentityAuth'
      # If pipeline is triggered by a new tag we only sync the tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
        arguments: '-SourceRepository "https://$(GitHubPAT)@github.com/microsoft/BCApps.git" -TargetRepository $(TargetRepository) -ManagedIdentityAuth'