name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number 

pr: none
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

pool:
  name: 'd365bc-agentpool-nonprod-bcapps-sync'

variables:
- template: ./variables-common.yml

jobs:
- job: SyncMirror
  dependsOn: []
  steps:
  - template: SyncMirror-Steps.yml
    parameters:
      SourceRepository: "https://$(GitHubPAT)@github.com/microsoft/BCApps.git"
      TargetRepository: "$(TargetRepository)"
      Branch: "$(Build.SourceBranch)"