name: Update Package Versions

on:
  workflow_dispatch:
  schedule:
    - cron: "55 03 * * 2" # Run at 03:55 UTC on Tuesday

defaults:
  run:
    shell: powershell

jobs:
  GetBranches:
    runs-on: windows-latest
    outputs:
      UpdateBranches: ${{ steps.GetBranches.outputs.UpdateBranches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Branches
        id: GetBranches
        run: |
          git fetch
          #$branches = @(git for-each-ref --format="'%(refname:short)'" refs/remotes/origin/release/ | % { $_ -replace 'origin/', '' })
          $branches += "'aholstrup/fetch_baseline_packages'"

          $branchMatrix = "[$($branches -join ',')]"
          Write-Host "Updating branches: $branchMatrix"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "UpdateBranches=$branchMatrix"

  UpdatePackageVersions:
    runs-on: windows-latest
    needs: GetBranches
    strategy:
      matrix:
        branch: ${{ fromJson(needs.GetBranches.outputs.UpdateBranches) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      
      - name: Update Package Versions
        run: | 
          Build/Scripts/UpdatePackageVersions.ps1 -TargetBranch ${{ matrix.branch }} -Actor $env:GITHUB_ACTOR
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
