name: Get Official Branches
author: Microsoft Corporation
description: Get the official branches in a repository
inputs:
  repository:
    description: The repository to get the official branches from
    required: true
    default: ${{ github.repository }}
outputs:
  OfficialBranches:
    description: The official branches in the repository
    value:  ${{ steps.GetBranches.outputs.OfficialBranches }}
runs:
  using: composite
  steps:
    - name: run
      shell: pwsh
      id: GetBranches
      env:
        GH_TOKEN: ${{ github.token }}
        _repository: ${{ inputs.repository }}
      run: |
        $branches = gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$($env:_repository)/branches?protected=true&per_page=100" | ConvertFrom-Json
        $branchNames = @($branches.name)

        if (-not $branchNames) {
            Write-Host "No official branches found, using main as default"
            $branchNames += "main"
        }
        Write-Host "Official branches: $($branchNames -join ', ')"

        $branchMatrix = ConvertTo-Json $branchNames -Compress
        Add-Content -Path $env:GITHUB_OUTPUT -Value "OfficialBranches=$branchMatrix"
branding:
  icon: terminal
  color: blue
