name: Get Official Branches
author: Microsoft Corporation
description: Get the official branches in a repository
inputs:
  repository:
    description: The repository to get the official branches from
    required: true
    default: ${{ github.repository }}
outputs:
  OfficialBranches:
    description: The official branches in the repository
    value:  ${{ steps.GetBranches.outputs.OfficialBranches }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: run
      shell: pwsh
      id: GetBranches
      env:
        GH_TOKEN: ${{ github.token }}
        _repository: ${{ inputs.repository }}
      run: |
        ${{ github.action_path }}/action.ps1
branding:
  icon: terminal
  color: blue
