name: Get Official Branches
author: Microsoft Corporation
description: Get the official branches in a repository
inputs:
  repository:
    description: The repository to get the official branches from
    required: true
    default: ${{ github.repository }}
outputs:
  OfficialBranches:
    description: The official branches in the repository
    value:  ${{ steps.GetBranches.outputs.OfficialBranches }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: run
      shell: pwsh
      id: GetBranches
      env:
        GH_TOKEN: ${{ github.token }}
        _repository: ${{ inputs.repository }}
      run: |
          git fetch
          $branches = @(git for-each-ref --format="'%(refname:short)'" refs/remotes/origin/releases/ | % { $_ -replace 'origin/', '' })
          $branches += "'main'"
          $branchMatrix = "[$($branches -join ',')]"

          Write-Host "Official branches: $branchMatrix"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "OfficialBranches=$branchMatrix"
branding:
  icon: terminal
  color: blue
